MIDI_RESOLUTION = 16
MICROSECONDS_PER_MINUTE = 60000000

MIDI_WHOLE = MIDI_RESOLUTION * 4
MIDI_HALF = MIDI_RESOLUTION * 2
MIDI_QUARTER = MIDI_RESOLUTION
MIDI_EIGHTH = int(MIDI_RESOLUTION * 0.5)
MIDI_SIXTEENTH = int(MIDI_RESOLUTION * 0.25)
MIDI_THIRTY_SECOND = int(MIDI_RESOLUTION * 0.125)
MIDI_SIXTY_FOURTH = int(MIDI_RESOLUTION * 0.0625)

WHOLE = 1
HALF = 2
QUARTER = 4
EIGHTH = 8
SIXTEENTH = 16
THIRTY_SECOND = 32
SIXTY_FOURTH = 64

MIN_OCTAVE = 0
MAX_OCTAVE = 8
NOTES_IN_OCTAVE = 12
