MIDI_RESOLUTION = 16

MIDI_WHOLE = MIDI_RESOLUTION * 4
MIDI_HALF = MIDI_RESOLUTION * 2
MIDI_QUARTER = MIDI_RESOLUTION
MIDI_EIGHTH = MIDI_RESOLUTION * 0.5
MIDI_SIXTEENTH = MIDI_RESOLUTION * 0.25
MIDI_THIRTY_SECOND = MIDI_RESOLUTION * 0.125
MIDI_SIXTY_FOURTH = MIDI_RESOLUTION * 0.0625

WHOLE = 1
HALF = 2
QUARTER = 4
EIGHTH = 8
SIXTEENTH = 16
THIRTY_SECOND = 32
SIXTY_FOURTH = 64
